### ISSUE TITLE
Possible Sync / Score Issues

### ISSUE THREAD

**Issue by Cyrris** [Uveso/AI-Uveso#2]
Hello! My friends and I play FAF every week. We do purely PvE, so your mod is quite valuable to us!

Since (approximately) the FAF 3715 milestone release, we've started having issues with score graphs not appearing. I know a fair bit of work was put in to 3715 to actually fix that problem (which was always intermittent anyway). I set aside some time to test this today, and I can only replicate the problem when Uveso AI mod is enabled.

I've attached 3 replays as an example, and my game.log file:

- 12734359 - Using no mods at all, everything runs as expected, score graphs appear.
- 12734373 - Using Uveso AI mod only, with one Uveso AIx: De-syncs not observed when playing, but exist in replay. No Score Graphs
- 12734388 - Using Uveso AI mod only, with one Sorian AIx: De-syncs not observed when playing, but exist in replay. No Score Graphs

I believe the replay Desync issue might be unrelated as it was first mentioned in August, prior to 3715: https://forums.faforever.com/viewtopic.php?f=88&t=16381&start=280 - and replays are not important to us anyway. However the score graph failures now appear to only occur when the Uveso AI mod is enabled (even if only using Sorian AI in-game). 

Knowing that you test each release very thoroughly, and that I've not seen anyone else reporting the score graph issue since 3715 was released, please let me know how I can do some better testing to help figure this one out.

[replays.zip](https://github.com/Uveso/AI-Uveso/files/5287857/replays.zip)
[game.log](https://github.com/Uveso/AI-Uveso/files/5287858/game.log)

**Comment by Uveso** [comment]
Thanks for reporting this.
As i know FAF changed something with scores to make it faster.
I will take a look at and fix it next week.

**Comment by Uveso** [comment]
Fixed in V88
